#!/usr/bin/env python3
#ledproc 1.0
#tezeta 2020

import mtxledctrl, os, threading, argparse, configparser, re, time

parser =  argparse.ArgumentParser(description='python led controller for certain Matrix Orbital displays using lcdproc',epilog='Parameters override any config found. Syntax for led: filename [color=r,g,o] [searchstring]')
parser.add_argument('-d', '--debug', action='store_true', default=False, help='Enable debug output')
parser.add_argument('-s', '--server', metavar='server', help='LCDd server', nargs=2, default=['127.0.0.1','13666'])
parser.add_argument('-u', '--update', metavar='option', help='Update interval', nargs=1, type=float, default=[0.5])
parser.add_argument('--led1', '-1', metavar='option', help='Control led1',nargs='+')
parser.add_argument('--led2', '-2', metavar='option', help='Control led2',nargs='+')
parser.add_argument('--led3', '-3', metavar='option', help='Control led3',nargs='+')
parser.add_argument('--config','-c', metavar='filename', help='Use config file', nargs=1, default=['/etc/ledproc.conf'])
args = parser.parse_args()
debugOn = args.debug

def debug(message):
    if debugOn:
        print("debug: " + str(message))
    return message

def info(message):
    print("info: " + str(message))
    return message

def error(message):
    print("ERROR: " + str(message))
    return message

def monitor(filename, color, searchstring, led):
    if (color != 'r') and (color != 'g') and (color != 'o'):
        raise AssertionError("Color " + color + " is not a valid color")

    i = ''
    info("opening " + filename + "[\"" + searchstring + "\"] using led " + str(led) + " with color " + color)
    while True:
        with open(filename, "r") as st:
            st = st.read()
            
            if searchstring:
                s = ""
                for line in st.splitlines():
                    if re.search(searchstring, line):
                        s += line
            else:
                s = st

            if s == "":
                raise IndexError("Substring " + searchstring + " doesn't exist in " + filename)

            if s != i: #contents have changed
                debug("change in file "+filename + "[" + searchstring +"] detected, flashing led " + str(led))
                mtxledctrl.queuecolor(led, color) #set flags based on LED and color requested
            
                mtxledctrl.sendcmd(tn) #flash LED
                time.sleep(args.update[0])

                mtxledctrl.queuecolor(led, "null")
                mtxledctrl.sendcmd(tn) #turn off LED
            i = s
            time.sleep(args.update[0])

def getcfg(filename):
    cfg = configparser.ConfigParser()
    ledargs = {}
    
    if os.path.exists(filename):
        try:
            debug(cfg.read(filename))
            for led in ['1','2','3']:
                ledargs['led'+led] = {}
                ledargs['led'+led]['filename'] = cfg.get('led'+led,'filename')
                ledargs['led'+led]['color'] = cfg.get('led'+led,'color')
                ledargs['led'+led]['searchstring'] = cfg.get('led'+led,'searchstring')
        except:
                pass
    try:
        if args.led1:
            ledargs['led1'] = {}
            ledargs['led1']['filename'] = args.led1[0]
            ledargs['led1']['color'] = args.led1[1].lower()
            ledargs['led1']['searchstring'] = args.led1[2]
        if args.led2:
            ledargs['led2'] = {}
            ledargs['led2']['filename'] = args.led2[0]
            ledargs['led2']['color'] = args.led2[1].lower()
            ledargs['led2']['searchstring'] = args.led2[2]
        if args.led3:
            ledargs['led3'] = {}
            ledargs['led3']['filename'] = args.led3[0]
            ledargs['led3']['color'] = args.led3[1].lower()
            ledargs['led3']['searchstring'] = args.led3[2]
    except:
        pass

    return debug(ledargs)

if __name__ == "__main__":
    info("initializing...")
    tn = mtxledctrl.init(args.server[0], args.server[1])
     
    leds={}
    ledargs=getcfg(str(args.config[0]))

    for led in ['1','2','3']:
        if not 'led' + led in ledargs or not 'filename' in ledargs['led'+led]:
            continue
        if not 'color' in ledargs['led'+led]:
            ledargs['led'+led]['color'] = 'o'
        if not 'searchstring' in ledargs['led'+led]:
            ledargs['led'+led]['searchstring'] = ''

        debug("Creating thread for LED" + led + " with arguments: " + str(ledargs['led'+led]))
        leds[led] = threading.Thread(target=monitor, args=(ledargs['led'+led]['filename'], ledargs['led'+led]['color'].lower(), ledargs['led'+led]['searchstring'], led))
        leds[led].start()
